name: build-xs-galactic

on:
  push:
    branches:
      - galactic
  pull_request:
    branches:
      - galactic
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  xs-galactic:
    strategy:
      matrix:
        env:
          - {ROS_DISTRO: galactic,  ROS_REPO: main}
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout ROS Manipulators
        uses: actions/checkout@v3
      - name: Run Install Script
        run: |
          chmod +x ./interbotix_ros_xsarms/install/amd64/xsarm_amd64_install.sh
          ./interbotix_ros_xsarms/install/amd64/xsarm_amd64_install.sh -n -d galactic
