name: build-xs-noetic

on:
  push:
    branches:
      - noetic
      - devel
  pull_request:
    branches:
      - noetic
      - devel
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  xs-noetic:
    strategy:
      matrix:
        env:
          - {ROS_DISTRO: noetic,  ROS_REPO: main, BUILDER: catkin_make}
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout ROS Manipulators
        uses: actions/checkout@v3
      - name: Run Install Script
        run: |
          chmod +x ./interbotix_ros_xsarms/install/amd64/xsarm_amd64_install.sh
          ./interbotix_ros_xsarms/install/amd64/xsarm_amd64_install.sh -n -d noetic
